"""Add code to authorization code

Revision ID: b8fd8a5cb0a1
Revises: e5372087492f
Create Date: 2023-08-23 19:29:45.256154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fd8a5cb0a1'
down_revision = 'e5372087492f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorizationcodes', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorizationcodes', 'code')
    # ### end Alembic commands ###
