"""Add many to many relationship user-permission

Revision ID: c90db4410eab
Revises: 8f0af5b4181a
Create Date: 2023-08-21 21:48:25.175618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90db4410eab'
down_revision = '8f0af5b4181a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.drop_constraint('permissions_owner_id_fkey', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'test')
    op.drop_column('permissions', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('permissions_owner_id_fkey', 'permissions', 'users', ['owner_id'], ['id'])
    op.drop_table('user_permission')
    # ### end Alembic commands ###
