"""Add authorization code

Revision ID: e5372087492f
Revises: c90db4410eab
Create Date: 2023-08-23 00:01:10.260620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5372087492f'
down_revision = 'c90db4410eab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorizationcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expire_on', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizationcodes_id'), 'authorizationcodes', ['id'], unique=False)
    op.create_table('authorizationcode_permission',
    sa.Column('authorization_code_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorization_code_id'], ['authorizationcodes.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('authorization_code_id', 'permission_id')
    )
    op.alter_column('clients', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_clients_id', table_name='clients')
    op.drop_column('clients', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.alter_column('clients', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('authorizationcode_permission')
    op.drop_index(op.f('ix_authorizationcodes_id'), table_name='authorizationcodes')
    op.drop_table('authorizationcodes')
    # ### end Alembic commands ###
